# Generated by Django 2.0.7 on 2018-07-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Programmes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level_of_programme', models.CharField(max_length=100)),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
            ],
        ),
    ]
