# Generated by Django 2.0.7 on 2018-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0003_advanced_dimploma_certificate_diploma_innovative_interdisciplinary_others_pg_pg_dimploma_ug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('faculty_name', models.CharField(max_length=100)),
                ('college_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='advanced_dimploma',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='advanced_dimploma',
            name='date',
        ),
        migrations.RemoveField(
            model_name='advanced_dimploma',
            name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='name',
        ),
        migrations.RemoveField(
            model_name='innovative',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='innovative',
            name='date',
        ),
        migrations.RemoveField(
            model_name='innovative',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interdisciplinary',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='interdisciplinary',
            name='date',
        ),
        migrations.RemoveField(
            model_name='interdisciplinary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='others',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='others',
            name='date',
        ),
        migrations.RemoveField(
            model_name='others',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pg',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='pg',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pg',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pg_dimploma',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='pg_dimploma',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pg_dimploma',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phd',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='phd',
            name='date',
        ),
        migrations.RemoveField(
            model_name='phd',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ug',
            name='college_id',
        ),
        migrations.RemoveField(
            model_name='ug',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ug',
            name='name',
        ),
    ]
