# Generated by Django 2.0.7 on 2018-07-16 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0005_auto_20180716_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
