# Generated by Django 2.0.7 on 2018-07-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0006_musician_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
