# Generated by Django 2.0.7 on 2018-07-16 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0007_auto_20180716_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advanced_Dimploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(default=0, max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Innovative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Interdisciplinary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='PG_Dimploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='PhD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='UG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AddField(
            model_name='diploma',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form'),
        ),
        migrations.AddField(
            model_name='advanced_dimploma',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form'),
        ),
    ]
