# Generated by Django 2.0.7 on 2018-07-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0009_form_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='form',
            name='question_text',
        ),
        migrations.AddField(
            model_name='form',
            name='college_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='faculty_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
