# Generated by Django 2.0.7 on 2018-07-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0010_auto_20180716_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
