# Generated by Django 2.0.7 on 2018-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0011_auto_20180716_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='college_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='form',
            name='faculty_name',
            field=models.CharField(max_length=100),
        ),
    ]
