# Generated by Django 2.0.7 on 2018-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0012_auto_20180716_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='create_date',
            field=models.DateTimeField(blank=True, verbose_name='date created'),
        ),
    ]
