# Generated by Django 2.0.7 on 2018-07-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0018_form_institute_institute_accreditation_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.RemoveField(
            model_name='institute_accreditation_details',
            name='institute',
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='Institute_accreditation_details',
        ),
    ]
