# Generated by Django 2.0.7 on 2018-07-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0020_form_institute_institute_accreditation_details_iqac_composition_activities_seminars_conferences_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='institute',
            name='iqac_funding_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='iqac_composition_activities',
            name='aqar_statutory_body_yes',
            field=models.CharField(choices=[('M', 'Management'), ('S', 'Syndicate'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
