# Generated by Django 2.0.7 on 2018-07-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0021_auto_20180720_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
