# Generated by Django 2.0.7 on 2018-07-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CriteriaForm', '0024_auto_20180723_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=1000)),
                ('address_line_2', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('college_email_address', models.EmailField(max_length=254)),
                ('head_of_institute', models.CharField(max_length=200)),
                ('telephone', models.PositiveIntegerField()),
                ('college_mobile', models.IntegerField()),
                ('iqac_coordinator', models.CharField(max_length=200)),
                ('coordinator_mobile', models.IntegerField()),
                ('iqac_email', models.EmailField(max_length=254)),
                ('naac_track_id', models.CharField(max_length=20)),
                ('naac_executive_committe_date', models.CharField(max_length=50)),
                ('college_website', models.URLField()),
                ('aqar_weblink', models.URLField()),
                ('date_of_iqac_establishment', models.DateField()),
                ('aqar_submission_1', models.CharField(max_length=100)),
                ('aqar_submission_2', models.CharField(max_length=100)),
                ('aqar_submission_3', models.CharField(max_length=100)),
                ('aqar_submission_4', models.CharField(max_length=100)),
                ('university', models.CharField(choices=[('S', 'State'), ('C', 'Central'), ('D', 'Deemed'), ('P', 'Private')], max_length=2)),
                ('Affiliated', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('Constituent', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('autonomous', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('regulatory_agency_approved', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('type_of_institution', models.CharField(choices=[('CO', 'Co-education'), ('M', 'Men'), ('W', 'Women'), ('U', 'Urban'), ('R', 'Rural'), ('T', 'Tribal')], max_length=2)),
                ('financial_status', models.CharField(choices=[('G', 'Grant-in-aid'), ('UF', 'UGC 2(f)'), ('UG', 'UGC 12B'), ('GS', 'Grant-in-aid + Self Financing'), ('TS', 'Totally Self-financing')], max_length=3)),
                ('type_of_faculty', models.CharField(choices=[('A', 'Arts'), ('S', 'Science'), ('C', 'Commerce'), ('L', 'Law'), ('P', 'PIE'), ('T', 'TEI'), ('E', 'Engineering'), ('HS', 'Health Science'), ('M', 'Management')], max_length=2)),
                ('type_of_faculty_others', models.CharField(max_length=100)),
                ('affiliating_university', models.CharField(max_length=200)),
                ('iqac_funding', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('iqac_funding_amount', models.IntegerField(null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='IQAC_composition_activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.IntegerField()),
                ('administrative_staff', models.IntegerField()),
                ('students', models.IntegerField()),
                ('management_representatives', models.IntegerField()),
                ('alumni', models.IntegerField()),
                ('stakeholder_community_representatives', models.IntegerField()),
                ('employers_industrialists', models.IntegerField()),
                ('external_experts', models.IntegerField()),
                ('total_members', models.IntegerField()),
                ('iqac_meetings_held', models.IntegerField()),
                ('activites_contributions', models.TextField()),
                ('plan_of_action', models.TextField()),
                ('achivements_by_year', models.TextField()),
                ('aqar_statutory_body', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('aqar_statutory_body_yes', models.CharField(choices=[('M', 'Management'), ('S', 'Syndicate'), ('O', 'Other')], max_length=1, null=True)),
                ('plan_of_action_taken', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Seminars_conferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('international', models.IntegerField()),
                ('national', models.IntegerField()),
                ('state', models.IntegerField()),
                ('institute', models.IntegerField()),
                ('themes', models.TextField()),
                ('IQAC_composition_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.IQAC_composition_activities')),
            ],
        ),
        migrations.CreateModel(
            name='Special_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomy', models.CharField(max_length=100)),
                ('university_excellence', models.CharField(max_length=100)),
                ('dst_star_schema', models.CharField(max_length=100)),
                ('ugc_sap', models.CharField(max_length=100)),
                ('ugc_ipp', models.CharField(max_length=100)),
                ('ugc_cop', models.CharField(max_length=100)),
                ('ugc_cpe', models.CharField(max_length=100)),
                ('ugc_ce', models.CharField(max_length=100)),
                ('dst_fist', models.CharField(max_length=100)),
                ('others', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholders_meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('faculty', models.IntegerField()),
                ('nonteaching_staff_students', models.IntegerField()),
                ('alumni', models.IntegerField()),
                ('others', models.IntegerField()),
                ('IQAC_composition_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.IQAC_composition_activities')),
            ],
        ),
        migrations.AddField(
            model_name='cycle4',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Institute'),
        ),
        migrations.AddField(
            model_name='cycle3',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Institute'),
        ),
        migrations.AddField(
            model_name='cycle2',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Institute'),
        ),
        migrations.AddField(
            model_name='cycle1',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CriteriaForm.Institute'),
        ),
    ]
