# Generated by Django 2.0.7 on 2018-07-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0025_auto_20180723_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle1',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='cycle2',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='cycle3',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='cycle4',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='form',
        ),
        migrations.RemoveField(
            model_name='iqac_composition_activities',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='seminars_conferences',
            name='IQAC_composition_activities',
        ),
        migrations.RemoveField(
            model_name='special_status',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='stakeholders_meetings',
            name='IQAC_composition_activities',
        ),
        migrations.AddField(
            model_name='institute',
            name='college_contact_no',
            field=models.IntegerField(default=0),
        ),
    ]
