# Generated by Django 2.0.7 on 2018-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0026_auto_20180723_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='college_contact_no',
            field=models.IntegerField(),
        ),
    ]
