# Generated by Django 2.0.7 on 2018-07-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0027_auto_20180723_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='aqar_for_year',
            field=models.CharField(default=9, max_length=100),
        ),
    ]
