# Generated by Django 2.0.7 on 2018-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0028_institute_aqar_for_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='aqar_for_year',
            field=models.CharField(max_length=100),
        ),
    ]
