# Generated by Django 2.0.7 on 2018-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0029_auto_20180723_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='type_of_faculty',
            field=models.CharField(choices=[('A', 'Arts'), ('S', 'Science'), ('C', 'Commerce'), ('L', 'Law'), ('P', 'PIE'), ('T', 'TEI'), ('E', 'Engineering'), ('HS', 'Health Science'), ('M', 'Management'), ('O', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='institute',
            name='type_of_faculty_others',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
