# Generated by Django 2.0.7 on 2018-07-28 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0031_auto_20180728_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='address_line_1',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
