# Generated by Django 2.0.7 on 2018-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0036_institute_college_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='college_contact_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
