# Generated by Django 2.0.7 on 2018-07-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0037_auto_20180728_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='Affiliated',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='Constituent',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='affiliating_university',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='aqar_for_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='aqar_submission_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='aqar_submission_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='aqar_submission_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='aqar_submission_4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='aqar_weblink',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='autonomous',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='college_mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='college_website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='coordinator_mobile',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='date_of_iqac_establishment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='financial_status',
            field=models.CharField(choices=[('G', 'Grant-in-aid'), ('UF', 'UGC 2(f)'), ('UG', 'UGC 12B'), ('GS', 'Grant-in-aid + Self Financing'), ('TS', 'Totally Self-financing')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='head_of_institute',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='iqac_coordinator',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='iqac_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='iqac_funding',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='iqac_funding_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='naac_executive_committe_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='naac_track_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='regulatory_agency_approved',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='telephone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='type_of_faculty',
            field=models.CharField(choices=[('A', 'Arts'), ('S', 'Science'), ('C', 'Commerce'), ('L', 'Law'), ('P', 'PIE'), ('T', 'TEI'), ('E', 'Engineering'), ('HS', 'Health Science'), ('M', 'Management'), ('O', 'Others')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='type_of_faculty_others',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='type_of_institution',
            field=models.CharField(choices=[('CO', 'Co-education'), ('M', 'Men'), ('W', 'Women'), ('U', 'Urban'), ('R', 'Rural'), ('T', 'Tribal')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='university',
            field=models.CharField(choices=[('S', 'State'), ('C', 'Central'), ('D', 'Deemed'), ('P', 'Private')], max_length=2, null=True),
        ),
    ]
