# Generated by Django 2.0.7 on 2018-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0038_auto_20180728_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='iqac_funding_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
