# Generated by Django 2.0.7 on 2018-07-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0039_auto_20180728_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='naac_executive_committe_date',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
