# Generated by Django 2.0.7 on 2018-07-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0041_remove_institute_date_of_iqac_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='Affiliated',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='Constituent',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='autonomous',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='iqac_funding',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='naac_track_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='regulatory_agency_approved',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='type_of_institution',
            field=models.CharField(choices=[('CO', 'Co-education'), ('M', 'Men'), ('W', 'Women'), ('U', 'Urban'), ('R', 'Rural'), ('T', 'Tribal')], max_length=4, null=True),
        ),
    ]
