# Generated by Django 2.0.7 on 2018-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0042_auto_20180728_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='date_of_iqac_establishment',
            field=models.DateField(null=True),
        ),
    ]
