# Generated by Django 2.0.7 on 2018-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0043_institute_date_of_iqac_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='date_of_iqac_establishment',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
