# Generated by Django 2.0.7 on 2018-07-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0044_auto_20180728_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cgpa', models.CharField(max_length=10)),
                ('year_of_accreditation', models.IntegerField()),
                ('validity_period', models.IntegerField()),
            ],
        ),
    ]
