# Generated by Django 2.1 on 2018-08-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0047_auto_20180814_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advanced_Dimploma',
            new_name='Advanced_Diploma',
        ),
        migrations.RenameModel(
            old_name='PG_Dimploma',
            new_name='PG_Diploma',
        ),
    ]
