# Generated by Django 2.1 on 2018-08-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0048_auto_20180816_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_of_existing_programmes', models.IntegerField()),
                ('Number_of_programmes_added_during_year', models.IntegerField()),
                ('Number_of_self_financing_programmes', models.IntegerField()),
                ('Number_of_value_added_career_Oriented_programmes', models.IntegerField()),
            ],
        ),
    ]
