# Generated by Django 2.1 on 2018-08-17 06:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0049_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria1',
            name='Feedback_stakeholders',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Alumni'), ('P', 'Parents'), ('E', 'Employers'), ('S', 'Students')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='criteria1',
            name='Mode_of_feedback',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('O', 'Online'), ('M', 'Manual'), ('C', 'Co-operating schools(for PEI)')], max_length=5, null=True),
        ),
    ]
