# Generated by Django 2.1 on 2018-08-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CriteriaForm', '0050_auto_20180817_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferences_organized_institution',
            name='Criteria3',
        ),
        migrations.RemoveField(
            model_name='funds_for_colleges',
            name='Criteria3',
        ),
        migrations.RemoveField(
            model_name='major_projects',
            name='Criteria3',
        ),
        migrations.RemoveField(
            model_name='minor_projects',
            name='Criteria3',
        ),
        migrations.RemoveField(
            model_name='research_publications',
            name='Criteria3',
        ),
        migrations.RemoveField(
            model_name='university_department_funds',
            name='Criteria3',
        ),
        migrations.DeleteModel(
            name='Conferences_organized_institution',
        ),
        migrations.DeleteModel(
            name='Criteria3',
        ),
        migrations.DeleteModel(
            name='Funds_For_colleges',
        ),
        migrations.DeleteModel(
            name='Major_projects',
        ),
        migrations.DeleteModel(
            name='Minor_projects',
        ),
        migrations.DeleteModel(
            name='Research_publications',
        ),
        migrations.DeleteModel(
            name='University_department_funds',
        ),
    ]
